name: Upload to Cloudflare R2 Test

on:
  push:
    branches:
      - main

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AWS CLI 2.10.0
        run: |
          sudo apt update -y
          sudo apt install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.10.0.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Sync files to Cloudflare R2
        run: |
          AWS_S3_CHECKSUM_MODE=disabled \
          aws s3 sync . s3://${{ secrets.AWS_SECRET_BUCKET_NAME }} \
            --endpoint-url=${{ secrets.AWS_SECRET_ENDPOINT }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "awscliv2.zip" \
            --exclude "README.md"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
