name: Mirror main branch to main-r2

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to main-r2
        run: |
          git remote add mirror https://${{ secrets.MIRROR_PAT }}@github.com/paul-qureskincare/main-r2.git
          git push mirror main:main --force -o skip-push-protection
